# language: generic

sudo: required
sevices:
    - docker

before_install:
    - docker build -t ben/docker-react -f Dockerfile.dev .

script:
    - docker run ben/docker-react npm run test -- --coverage
    # - docker run -e CI=true ben/docker-react npm run test