# language: generic

sudo: required
sevices:
    - docker

before_install:
    - docker build -t ben/docker-react -f Dockerfile.dev .

script:
    # - docker run ben/docker-react npm run test -- --coverage
    - docker run -e CI=true ben/docker-react npm run test

deploy:
    # edge: true
    provider: elasticbeanstalk 
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-853813081120"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_key_id: $AWS_SECRET_KEY
        # secure: "$AWS_SECRET_KEY"
    # my url: DockerReact-env.eba-cxn5mfmr.us-east-2.elasticbeanstalk.com